/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MyContractInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "add"
      | "add_en"
      | "add_encry"
      | "div"
      | "div_en"
      | "div_encry"
      | "mul"
      | "mul_en"
      | "mul_encry"
      | "perform"
      | "print"
      | "sub"
      | "sub_en"
      | "sub_encry"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "add",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "add_en",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "add_encry",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "div",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "div_en",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "div_encry",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mul",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mul_en",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mul_encry",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "perform", values?: undefined): string;
  encodeFunctionData(functionFragment: "print", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "sub",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sub_en",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sub_encry",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "add", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "add_en", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "add_encry", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "div", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "div_en", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "div_encry", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mul", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mul_en", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mul_encry", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "perform", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "print", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sub", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sub_en", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sub_encry", data: BytesLike): Result;
}

export interface MyContract extends BaseContract {
  connect(runner?: ContractRunner | null): MyContract;
  waitForDeployment(): Promise<this>;

  interface: MyContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  add: TypedContractMethod<
    [e1: BigNumberish, e2: BigNumberish],
    [bigint],
    "view"
  >;

  add_en: TypedContractMethod<
    [e1: BigNumberish, e2: BytesLike],
    [bigint],
    "view"
  >;

  add_encry: TypedContractMethod<
    [e1: BytesLike, e2: BytesLike],
    [bigint],
    "view"
  >;

  div: TypedContractMethod<
    [e1: BigNumberish, e2: BigNumberish],
    [bigint],
    "view"
  >;

  div_en: TypedContractMethod<
    [e1: BigNumberish, e2: BytesLike],
    [bigint],
    "view"
  >;

  div_encry: TypedContractMethod<
    [e1: BytesLike, e2: BytesLike],
    [bigint],
    "view"
  >;

  mul: TypedContractMethod<
    [e1: BigNumberish, e2: BigNumberish],
    [bigint],
    "view"
  >;

  mul_en: TypedContractMethod<
    [e1: BigNumberish, e2: BytesLike],
    [bigint],
    "view"
  >;

  mul_encry: TypedContractMethod<
    [e1: BytesLike, e2: BytesLike],
    [bigint],
    "view"
  >;

  perform: TypedContractMethod<[], [void], "nonpayable">;

  print: TypedContractMethod<[], [bigint], "view">;

  sub: TypedContractMethod<
    [e1: BigNumberish, e2: BigNumberish],
    [bigint],
    "view"
  >;

  sub_en: TypedContractMethod<
    [e1: BigNumberish, e2: BytesLike],
    [bigint],
    "view"
  >;

  sub_encry: TypedContractMethod<
    [e1: BytesLike, e2: BytesLike],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "add"
  ): TypedContractMethod<
    [e1: BigNumberish, e2: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "add_en"
  ): TypedContractMethod<[e1: BigNumberish, e2: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "add_encry"
  ): TypedContractMethod<[e1: BytesLike, e2: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "div"
  ): TypedContractMethod<
    [e1: BigNumberish, e2: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "div_en"
  ): TypedContractMethod<[e1: BigNumberish, e2: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "div_encry"
  ): TypedContractMethod<[e1: BytesLike, e2: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "mul"
  ): TypedContractMethod<
    [e1: BigNumberish, e2: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "mul_en"
  ): TypedContractMethod<[e1: BigNumberish, e2: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "mul_encry"
  ): TypedContractMethod<[e1: BytesLike, e2: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "perform"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "print"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "sub"
  ): TypedContractMethod<
    [e1: BigNumberish, e2: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "sub_en"
  ): TypedContractMethod<[e1: BigNumberish, e2: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "sub_encry"
  ): TypedContractMethod<[e1: BytesLike, e2: BytesLike], [bigint], "view">;

  filters: {};
}
